import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function AuthLayout({
                                      children,
                                  }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <header>
            <h1>Login</h1>
        </header>
        <body className={"bg-green-600" }>{children}</body>
        </html>
    )
}
